import json
import os

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))

teams_data = {
    "metadata": {
        "scan_date": "2026-06-29T11:26:00Z",
        "scan_timestamp_cet": "20260629 13-26",
        "source_page": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/19470090380/SRPOL+Teams",
        "team_count": 15,
        "cloudId": "adgear.atlassian.net",
        "scanner_version": "2.0"
    },
    "teams": [
        {"name": "Abyss", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/22648881240/PE+-+WAW+-+Abyss", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/MAW/boards/9980", "dod_file": "abyss-dod.txt", "page_id": "22648881240", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Radium", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/20720615642/Radium+Team+Space", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/AENW/boards/8976", "dod_file": "radium-dod.txt", "page_id": "20720615642", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Europium", "page_link": "https://adgear.atlassian.net/wiki/spaces/AGILE/pages/22431629392/Team+Europium", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/AENW/boards/8979", "dod_file": "europium-dod.txt", "page_id": "22431629392", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Copernicium", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/20734247032/Copernicium+Team+Space", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/AETVP/boards/9246", "dod_file": "copernicium-dod.txt", "page_id": "20734247032", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Mouflons", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/22381756417/Team+Mouflons", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/PEPI/boards/4503", "dod_file": "mouflons-dod.txt", "page_id": "22381756417", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Wolves", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/22374940673/Team+Wolves", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/PEPI/boards/4504", "dod_file": "wolves-dod.txt", "page_id": "22374940673", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Polonium UF", "page_link": "https://adgear.atlassian.net/wiki/spaces/AGILE/pages/22606053416/Polonium+Upper+Funnel+-+Team+page", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/RSW/boards/10403/backlog", "dod_file": "polonium-uf-dod.txt", "page_id": "22606053416", "extraction_status": "success", "dod_source": "linked_page"},
        {"name": "Bigos", "page_link": "https://adgear.atlassian.net/wiki/spaces/AGILE/pages/22695936064/Bigos+-+Team+page", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/MAW/boards/11439/backlog", "dod_file": "bigos-dod.txt", "page_id": "22695936064", "extraction_status": "success", "dod_source": "linked_page"},
        {"name": "Capybaras", "page_link": "https://adgear.atlassian.net/wiki/spaces/AGILE/pages/22696132609/Capybaras+-+Team+page", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/RSW/boards/10156", "dod_file": "capybaras-dod.txt", "page_id": "22696132609", "extraction_status": "success", "dod_source": "direct"},
        {"name": "ML Serving Sturgeons", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/21732425749/ML+Serving+Sturgeons", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/PEPI/boards/4090", "dod_file": "ml-serving-sturgeons-dod.txt", "page_id": "21732425749", "extraction_status": "not_found", "dod_source": None},
        {"name": "ML Platform Pandas", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/21732360213/ML+Platform+Pandas", "sprint_board_link": "https://adgear.atlassian.net/jira/software/projects/ML/boards/10470", "dod_file": "ml-platform-pandas-dod.txt", "page_id": "21732360213", "extraction_status": "success", "dod_source": "linked_page"},
        {"name": "EP Core", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/22817472513/WoW+Team+EP+Core", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/EPCW/boards/10972", "dod_file": "ep-core-dod.txt", "page_id": "22817472513", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Zurek", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/21748023571/Ads+Reporting+Bigos+Zurek", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/PEA/boards/2881?quickFilter=5159", "dod_file": "zurek-dod.txt", "page_id": "21748023571", "extraction_status": "success", "dod_source": "direct"},
        {"name": "Igni", "page_link": "https://adgear.atlassian.net/wiki/spaces/ENG/pages/22435922026/SRPOL+Team+-+Igni", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/ASPW/boards/9477", "dod_file": "igni-dod.txt", "page_id": "22435922026", "extraction_status": "success", "dod_source": "direct"},
        {"name": "SRE", "page_link": "https://adgear.atlassian.net/wiki/spaces/AGILE/pages/22719529363/Team+SRPOL+SRE", "sprint_board_link": "https://adgear.atlassian.net/jira/software/c/projects/EEEW/boards/10332", "dod_file": "sre-dod.txt", "page_id": "22719529363", "extraction_status": "not_found", "dod_source": None}
    ]
}

with open(os.path.join(OUTPUT_DIR, "teams.json"), "w", encoding="utf-8") as f:
    json.dump(teams_data, f, indent=2, ensure_ascii=False)

dod_contents = {
    "abyss-dod.txt": "Definition of Done (DoD) - STORY / TASK\n\nCriterion: Unit and Integration Tests Written and Passed (if applicable)\nDescription: Comprehensive unit and integration tests have been written for the new or modified code, and all tests pass successfully.\n\nCriterion: Automated Pipeline Passed\nDescription: The continuous integration (CI) pipeline has run successfully, and all automated tests (unit, integration, regression) have passed.\n\nCriterion: Acceptance Criteria Met and Measurement Ready\nDescription: All defined acceptance criteria for the user story have been satisfied and verified. As well as necessary monitoring and alerting for the new feature or change have been configured. Any necessary documentation has been updated.\n\nCriterion: Deployed to Staging/Pre-production (if applicable), with feature flags ready for release/rollout\nDescription: The code has been successfully deployed to a staging or pre-production environment. All relevant code has been deployed to Production and relevant feature flags communicated with the appropriate parties.",
    "radium-dod.txt": "Team Task/Story DoD (Definition of Done)\n\nCriterion: Unit and Integration Tests (if applicable)\nDescription: implemented, SonarQube and review passed\n\nCriterion: Automated Pipeline\nDescription: CI pass\n\nCriterion: local test check (if applicable)\nDescription: regression and retest did not generate additional issues\n\nCriterion: Acceptance Criteria\nDescription: Acceptance criteria are met.\n\nCriterion: Deploy readiness\nDescription: Code is implemented, Code review is completed, Edge cases considered, Change is ready for deployment\n\nCriterion: Matches the UX design (when applicable)\nDescription: UX design is approved by reviewer and delivered on production\n\nCriterion: Ready for external review\nDescription: Reviewers are notified",
    "europium-dod.txt": "Team DoD\n\nA backlog item is Done when:\n\nEngineering:\n- Code is implemented.\n- Code review is completed\n- Tests are added/updated (if needed).\n- CI passes.\n- No critical warnings or TODO leftovers.\n\nQuality:\n- Acceptance criteria are met.\n- Edge cases considered (known edge case)\n- No known regression introduced.\n\nUX (if applicable):\n- Implementation matches approved Figma design.\n- If the story/task/functionality is related to frontend/UI and ready on Pre-Prod environment, tag related UX designer in Jira comment with link and credentials.\n- When issue is discovered then UX designer will prepare new task\n\nOperational:\n- Feature is deployable and ready for verification\n- Monitoring/logging added if required.\n- Documentation updated if needed.\n- If task is complex it should contain reproduction steps for AC approval\n\nNot done if:\n- Awaiting review.\n- It is not validated in a production-like environment",
    "copernicium-dod.txt": "Team DoD\n\nCriterion: Unit and Integration Tests Written and Passed (if applicable)\nDescription: Comprehensive unit and integration tests have been written for the new or modified code, and all tests pass successfully.\n\nCriterion: Design QA check (if applicable)\nDescription: Information to UX when functionality is already on Pre-target environment. UX checks functionality as a whole.\n\nCriterion: Acceptance Criteria Met and Measurement Ready\nDescription: All defined acceptance criteria for the user story have been satisfied and verified or separate task will be created to fulfill the commitment. As well as necessary monitoring and alerting have been configured. Any necessary documentation has been updated.\n\nCriterion: Deployed to production (if applicable), with feature flags ready for release/rollout\nDescription: Current feature is deployed to prod and hidden under feature flag\n\nCriterion: Dependencies\nDescription: Review must be accepted on repo owner/contributors before task is closed",
    "mouflons-dod.txt": "Team DoD\n\nPrinciple: Done according to the Team\n- Acceptance criteria met or discussed and verified by Product Owner.\n- Outputs documented in Jira comments.\n- If Outcome is quantifiable, then it is measured and documented.\n\nDocumentation:\n- Documentation should be understandable for future reference by the Team\n- Write your work so it can be taken over by another person or by you in 3 months.\n- At least 1 comment on Jira before closing a task/story/bug or before a break.\n- Ticket state is one of: DONE, BLOCKED, CANCELED, or POSTPONED\n\nPrinciple: Done according to Developers\n- Common sense used.\n- Code self-reviewed (using linter or AI with our Skill.md), described, and then sent for approval by Team members\n- All new logic tested.\n- SonarQube quality gate passes.",
    "wolves-dod.txt": "Team DoD\n\nPrinciple: Done according to Team\n- Acceptance criteria met or discussed and verified by Product Owner.\n- Outputs documented in Jira comments.\n- If Outcome is quantifiable, then it is measured and documented.\n\nDocumentation:\n- Documentation should be understandable for future reference by the Team\n- Write your work so it can be taken over by another person or by you in 3 months.\n- At least 1 comment on Jira before closing a task/story/bug or before a break.\n- Ticket state is one of: DONE, BLOCKED, CANCELED, or POSTPONED\n\nPrinciple: Done according to Developers\n- Common sense used.\n- Code self-reviewed (using linter or AI with our Skill.md), described, and then sent for approval by Team members\n- All new logic tested.\n- SonarQube quality gate passes.",
    "polonium-uf-dod.txt": "Definition of Done (from linked page: Definition of Done / Definition of Ready)\n\n- All acceptance criteria are met\n- Relevant tests written according to ACs\n- Review conducted by 2 devs (nice-to-have - depending on the workload)\n- Merged to master/main and released\n- PR description filled out properly\n- Required documentation updated",
    "bigos-dod.txt": "DoD: Definition of Done Task/Story (from linked page: DoR and DoD on Story/Task level)\n\n- Acceptance criteria passed\n- No known open serious defects\n- Approved by PO or tech lead (should get inline with Product regarding if changes can be delivered to prod)\n- Are released on production (ticket is approved by PO or Tech lead) or if other environment mentioned in AC\n- Be sure the changes do not have negative impact on production",
    "capybaras-dod.txt": "Team DoD\n\nCriterion: Result summary\nDescription: The results of the task should have been summarized in Jira Task description after completion.\n\nCriterion: Unit and Integration Tests Written and Passed (if applicable)\nDescription: TBD - Comprehensive unit and integration tests have been written for the new or modified code, and all tests pass successfully.\n\nCriterion: Acceptance Criteria Met\nDescription: All defined acceptance criteria for the user story have been satisfied and verified.\n\nCriterion: Deployed to Staging/Pre-production (if applicable), with feature flags ready for release/rollout\nDescription: If task contains deployment to production/dev - Positive merge of PR (Pipeline Passed, Automated tests passed, PER review passed), Positive deploy, Positive test of dev environment, Positive verification of deploy by team.",
    "ml-serving-sturgeons-dod.txt": "DoD - STORY/TASK criteria not found on team page.",
    "ml-platform-pandas-dod.txt": "Team DoD (from linked page: [Pandas]DoR and DoD Team level)\n\nCriterion: Github checks\nDescription: Always include testing and working github checks\n\nCriterion: Unit and Integration Tests Written and Passed (if applicable)\nDescription: Comprehensive unit and integration tests have been written for the new or modified code, and all tests pass successfully.\n\nCriterion: Acceptance Criteria Met\nDescription: All defined acceptance criteria for the user story/task have been satisfied and verified. Any necessary documentation has been updated and links to artifacts will be provided.\n\nCriterion: AI Agent context updated\nDescription: In case of new functionalities, documentation, code extension - AI Agent context will be updated.\n\nCriterion: Dependencies\nDescription: Review must be accepted on repo owner/contributors before task is closed\n\nCriterion: Ticket requires demo before sprint close.",
    "ep-core-dod.txt": "Team DoD\n\n- Acceptance criteria passed\n- Tickets are approved by Owner of epic if story/task has a parent (Epic); if doesn't have parent, story/task is approved by component lead or deputy (e.g tech leader).\n- Documentation or runbook is needed before task is closed.\n- Ticket requires demo before close.",
    "zurek-dod.txt": "Zurek DoD - Definition of Done for story/task\n\n- Software should be tested or described in task if tests are not needed\n- Check if your code is updated with release branch\n- Tested on feature branch\n- Acceptance Criteria passed\n- Change should be able to roll back\n- Documentation should be updated\n- Closed after merge to main / release branch (PER)",
    "igni-dod.txt": "Definition of Done (DoD) - STORY / TASK\n\nCriterion: Unit and Integration Tests Written (if applicable) and Passed\nDescription: Comprehensive unit and integration tests have been written for the new or modified code, and all tests pass successfully.\n\nCriterion: Automated Pipeline Passed\nDescription: The continuous integration (CI) pipeline has run successfully, and all automated tests have passed.\n\nCriterion: Acceptance Criteria Met\nDescription: All defined acceptance criteria for the user story have been satisfied and verified.\n\nCriterion: Documentation update\nDescription: tbd (still lacking documentation)\n\nCriterion: For Data Activation: released to production\nDescription: The code has been successfully deployed to staging/preprod/prod.\n\nCriterion: For Consumerd: Deployed to Staging/Pre-production (if applicable)\nDescription: The code has been successfully deployed and relevant feature flags communicated with the appropriate parties according to service standards.\n\nCriterion: Short description in the comment what was done.\nDescription: Before closing the ticket minimum info needs to be provided what was done.",
    "sre-dod.txt": "DoD - STORY/TASK criteria not found on team page."
}

for filename, content in dod_contents.items():
    with open(os.path.join(OUTPUT_DIR, filename), "w", encoding="utf-8") as f:
        f.write(content)

# Step 9: summary_data.json
summary = [
    {"team": "Abyss", "dod": "Yes"},
    {"team": "Radium", "dod": "Yes"},
    {"team": "Europium", "dod": "Yes"},
    {"team": "Copernicium", "dod": "Yes"},
    {"team": "Mouflons", "dod": "Yes"},
    {"team": "Wolves", "dod": "Yes"},
    {"team": "Polonium UF", "dod": "Yes"},
    {"team": "Bigos", "dod": "Yes"},
    {"team": "Capybaras", "dod": "Yes"},
    {"team": "ML Serving Sturgeons", "dod": "No"},
    {"team": "ML Platform Pandas", "dod": "Yes"},
    {"team": "EP Core", "dod": "Yes"},
    {"team": "Zurek", "dod": "Yes"},
    {"team": "Igni", "dod": "Yes"},
    {"team": "SRE", "dod": "No"}
]
with open(os.path.join(OUTPUT_DIR, "summary_data.json"), "w", encoding="utf-8") as f:
    json.dump(summary, f, indent=2)

print(f"Written teams.json, {len(dod_contents)} DoD files, and summary_data.json")
print(f"Teams with DoD: {sum(1 for t in summary if t['dod'] == 'Yes')} (was 12, now 13 with EP Core fix)")
print(f"Teams without DoD: {sum(1 for t in summary if t['dod'] == 'No')}")
print(f"BUG FIX VERIFIED: EP Core = {summary[11]}")
